version: '3'
services:
  web:
    image: web:1.0
    container_name: web
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    ports:
      - "80:8000"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web